global:
  parameters: {}
  regions:
    - us-east-1
plans:
  production:
    parameters:
      NumCacheNodes: 2
      EngineVersion: "1.4.34"
      CacheNodeType: "cache.m4.large"
      AccessCidr: "10.0.0.0/16"