apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: aws-redis
  namespace: test-redis
spec:
  clusterServiceClassExternalName: awsredis 
  clusterServicePlanExternalName: production 
  parameters:
    VpcId: vpc-0f59e1f5e6fd508d5 
    SubnetA: subnet-00c4b46f45b847fd2 
    SubnetB: subnet-06aa0a6732bfc2dc7 
    SubnetC: subnet-038801806dfc1cb67
    TransitEncryptionEnabled: true 	
    AtRestEncryptionEnabled: true 
    ElasticCacheTags: testredis
