AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Cloudformation template for Dragonfly MSK service
Metadata:
  AWS::ServiceBroker::Specification:
    Version: 1.0
    Tags:
      - AWS
      - MSK
      - msk
      - awsmsk
    Name: awsmsk
    DisplayName: awsmsk
    LongDescription: >-
      MSK long description
    DocumentationUrl: https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/GettingStarted.html
    ProviderDisplayName: Amazon Web Services
    ServicePlans:
      production:
        DisplayName: Production
        Description: Configuration designed for production deployments
        LongDescription: Creates an Amazon msk optimised for
          production use
        Cost: https://aws.amazon.com/elasticache/pricing/
        ParameterValues: {}
      custom:
        DisplayName: Custom
        Description: Custom Configuration for Advanced deployments
        LongDescription: Creates an Amazon MSK with custom configuration
        Cost: https://aws.amazon.com/elasticache/pricing/
        ParameterValues: {}
Parameters:
  SubnetA:
    Description: >-
      One of the subnets you would like the Kafka deployment to use.
      In this Dragonfly deployment we only accept 3 subnets for now
    Type: 'AWS::EC2::Subnet::Id'
  SubnetB:
    Description: >-
      One of the subnets you would like the Kafka deployment to use.
      In this Dragonfly deployment we only accept 3 subnets for now
    Type: 'AWS::EC2::Subnet::Id'
  SubnetC:
    Description: >-
      One of the subnets you would like the Kafka deployment to use.
      In this Dragonfly deployment we only accept 3 subnets for now
    Type: 'AWS::EC2::Subnet::Id'
  ClusterName:
    Description: >-
        Logical cluster name for the MSK to be created
    Type: 'String'
  KafkaClientInstanceSecurityGroup:
    Description: >-
       Security Group id that is associated with the Client pod
    Type: AWS::EC2::SecurityGroup::Id
  VPCID:
    Description: >-
       VPC ID of where the cluster will be deployed
    Type: 'String'
  InstanceType:
    Description: The instance type the Kafka will launch under.
    Type: String
    Default: kafka.m5.large
    AllowedValues:
      - kafka.m5.large
      - kafka.m5.xlarge
      - kafka.m5.2xlarge
      - kafka.m5.2xlarge
      - kafka.m5.12xlarge
      - kafka.m5.24xlarge
  VolumeSize:
    Description: The size in GiB of the EBS volume for the data drive on each broker node.
    Type: Number
    Default: '2000'
    MinValue: '2000'
  JmxExporter:
    Description: Indicates whether you want to enable or disable JmxExporter
    Type: String
    Default: false
    AllowedValues: [true, false]
  NodeExporter:
    Description: Indicates whether you want to enable or disable the Node Exporter.
    Type: String
    Default: false
    AllowedValues: [true, false]   
  InCluster:
    Description: >-
      When set to true, it indicates that data communication among the broker nodes 
      of the cluster is encrypted. When set to false, the communication happens in plaintext. 
    Type: String
    Default: false
    AllowedValues: [true, false]
  ClientBroker:
    Description: >-
      Indicates the encryption setting for data in transit between clients and brokers. 
      The following are the possible values - TLS, TLS_PLAINTEXT,PLAINTEXT.
    Type: String
    Default: TLS_PLAINTEXT
    AllowedValues: [TLS, TLS_PLAINTEXT,PLAINTEXT]   
Resources:
  MSKSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable access to the MSK cluster
      VpcId: !Ref VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 2181
          ToPort: 2181
          SourceSecurityGroupId: !Ref KafkaClientInstanceSecurityGroup
        - IpProtocol: tcp
          FromPort: 9094
          ToPort: 9094
          SourceSecurityGroupId: !Ref KafkaClientInstanceSecurityGroup
        - IpProtocol: tcp
          FromPort: 9092
          ToPort: 9092
          SourceSecurityGroupId: !Ref KafkaClientInstanceSecurityGroup
  MSKCluster:
    Type: 'AWS::MSK::Cluster'
    Properties:
      BrokerNodeGroupInfo:
        ClientSubnets:
          - !Ref SubnetA
          - !Ref SubnetB
          - !Ref SubnetC
        InstanceType: !Ref InstanceType
        SecurityGroups:
          - !GetAtt
            - MSKSecurityGroup
            - GroupId
        StorageInfo:
          EBSStorageInfo:
            VolumeSize: !Ref VolumeSize
      ClusterName: !Ref ClusterName
      EncryptionInfo:
        EncryptionInTransit:
          ClientBroker: PLAINTEXT
          InCluster: !Ref InCluster
      EnhancedMonitoring: PER_TOPIC_PER_BROKER
      KafkaVersion: 2.2.1
      NumberOfBrokerNodes: 3
      OpenMonitoring:
        Prometheus:
          JmxExporter:
            EnabledInBroker: !Ref JmxExporter
          NodeExporter:
            EnabledInBroker: !Ref NodeExporter      
Outputs:
  MSKClusterArn:
    Description: The Arn for MSK cluster
    Value: !Ref MSKCluster
  MSKSecurityGroupID:
    Description: The ID of the security group created for the MSK clusters
    Value: !GetAtt
      - MSKSecurityGroup
      - GroupId
