AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Cloudformation template for Dragonfly MSK service
Metadata:
  AWS::ServiceBroker::Specification:
    Version: 1.0
    Tags:
      - AWS
      - MSK
      - msk
    Name: awsmsk
    DisplayName: awsmsk
    LongDescription: >-
      MSK long description
    DocumentationUrl: https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/GettingStarted.html
    ProviderDisplayName: Amazon Web Services
    ServicePlans:
      production:
        DisplayName: Production
        Description: Configuration designed for production deployments
        LongDescription: Creates an Amazon msk optimised for
          production use
        Cost: https://aws.amazon.com/elasticache/pricing/
        ParameterValues: {}
      custom:
        DisplayName: Custom
        Description: Custom Configuration for Advanced deployments
        LongDescription: Creates an Amazon MSK with custom configuration
        Cost: https://aws.amazon.com/elasticache/pricing/
        ParameterValues: {}
Parameters:
  SubnetA:
    Description: >-
      One of the subnets you would like the Kafka deployment to use.
      In this Dragonfly deployment we only accept 3 subnets for now
    Type: 'AWS::EC2::Subnet::Id'
  SubnetB:
    Description: >-
      One of the subnets you would like the Kafka deployment to use.
      In this Dragonfly deployment we only accept 3 subnets for now
    Type: 'AWS::EC2::Subnet::Id'
  SubnetC:
    Description: >-
      One of the subnets you would like the Kafka deployment to use.
      In this Dragonfly deployment we only accept 3 subnets for now
    Type: 'AWS::EC2::Subnet::Id'
  ClusterName:
    Description: >-
        Logical cluster name for the MSK to be created
    Type: 'String'
  KafkaClientInstanceSecurityGroup:
    Description: >-
       Security Group id that is associated with the Client pod
    Type: AWS::EC2::SecurityGroup::Id
  VPCID:
    Description: >-
       VPC ID
    Type: 'String'
  InstanceType:
    Description: The instance type the Kafka will launch under.
    Type: String
    Default: kafka.m5.large
    AllowedValues:
      - kafka.m5.large
      - kafka.m5.xlarge
      - kafka.m5.2xlarge
      - kafka.m5.2xlarge
      - kafka.m5.12xlarge
      - kafka.m5.24xlarge
Resources:
  MSKSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable access to the MSK cluster
      VpcId: !Ref VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 2181
          ToPort: 2181
          SourceSecurityGroupId: !Ref KafkaClientInstanceSecurityGroup
        - IpProtocol: tcp
          FromPort: 9094
          ToPort: 9094
          SourceSecurityGroupId: !Ref KafkaClientInstanceSecurityGroup
        - IpProtocol: tcp
          FromPort: 9092
          ToPort: 9092
          SourceSecurityGroupId: !Ref KafkaClientInstanceSecurityGroup
  MSKCluster:
    Type: 'AWS::MSK::Cluster'
    Properties:
      BrokerNodeGroupInfo:
        ClientSubnets:
          - !Ref SubnetA
          - !Ref SubnetB
          - !Ref SubnetC
        InstanceType: !Ref InstanceType
        SecurityGroups:
          - !GetAtt
            - MSKSecurityGroup
            - GroupId
        StorageInfo:
          EBSStorageInfo:
            VolumeSize: 2000
      ClusterName: !Ref ClusterName
      EncryptionInfo:
        EncryptionInTransit:
          ClientBroker: PLAINTEXT
          InCluster: false
      EnhancedMonitoring: PER_TOPIC_PER_BROKER
      KafkaVersion: 2.2.1
      NumberOfBrokerNodes: 3
Outputs:
  MSKClusterArn:
    Description: The Arn for MSK cluster
    Value: !Ref MSKCluster
  MSKSecurityGroupID:
    Description: The ID of the security group created for the MSK clusters
    Value: !GetAtt
      - MSKSecurityGroup
      - GroupId
