apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: elasticredis-instance-custom 
  namespace: test-redis
spec:
  clusterServiceClassExternalName: elasticredis
  clusterServicePlanExternalName: custom 
  parameters:
    ParentVPCStack: vpc-redis 
    ParentClientStack: client-sg-1 

  
